ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
  FORWARD_STEP_SIZE: 0.5
  TURN_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 1.0
  SENSORS: [
    IMAGEGOAL_SENSOR_V2,
    # SPECTROGRAM_SENSOR,
    # INSTRUCTION_SENSOR,
    # SHORTEST_PATH_SENSOR,
    # VLN_ORACLE_PROGRESS_SENSOR
    GLOBAL_GPS_SENSOR,
    HEADING_SENSOR,
    PANO_ANGLE_FEATURE_SENSOR,
    # VLN_ORACLE_WAYPOINT_SENSOR
  ]
  # INSTRUCTION_SENSOR_UUID: instruction
  POSSIBLE_ACTIONS: [STOP, GO_TOWARD_POINT]
  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL,
    # NDTW,
    PATH_LENGTH,
    ORACLE_SUCCESS,
    STEPS_TAKEN,
    WAYPOINT_REWARD_MEASURE,
  ]
  GLOBAL_GPS_SENSOR:
    DIMENSIONALITY: 2
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  SPL:
    SUCCESS_DISTANCE: 1.0
  NDTW:
    GT_PATH: data/datasets/R2R_VLNCE_v1-2_preprocessed/{split}/{split}_gt.json.gz

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz

