BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_waypoint_task.yaml
TRAINER_NAME: ddppo-waypoint-tf
ENV_NAME: VLNCEWaypointEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 10
TENSORBOARD_DIR: data/tensorboard_dirs/220917_1/c3/2e-4
CHECKPOINT_FOLDER: data/checkpoints/220917_1/c3/2e-4
EVAL_CKPT_PATH_DIR: data/checkpoints/220917_1/c3/2e-4
# TENSORBOARD_DIR: data/tensorboard_dirs/debug
# CHECKPOINT_FOLDER: data/checkpoints/debug
# EVAL_CKPT_PATH_DIR: data/checkpoints/debug

VISIBLE_GPUS: [0,1,2,3]

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ObsStack]

  PPO:
    pano_entropy_coef: 1.5
    offset_entropy_coef: 1.0
    lr: 2.5e-4
    num_mini_batch: 5
    num_steps: 40

  DDPPO:
    start_from_requeue: True
    requeue_path: data/checkpoints/220917_1/amain/2e-4/ckpt.27.pth
MODEL:
  policy_name: WaypointPolicyTF

  WAYPOINT:
    predict_distance: False
    min_offset_var: 0.00030625  # stddev of 1 degree
    max_offset_var: 0.06853892  # stddev of (range / 2)
    offset_temperature: 4.0

  INSTRUCTION_ENCODER:
    bidirectional: True
    final_state_only: False

  RGB_ENCODER:
    cnn_type: TorchVisionResNet18
    output_size: 256

  DEPTH_ENCODER:
    output_size: 256

  STATE_ENCODER:
    hidden_size: 256

